#!/usr/bin/env python
# encoding: utf-8


def build(ctx):
    ctx.program(
        target="ant",
        source = [
            "args.cpp",
            "main.cpp",
        ],
        lib=[
            "jsoncpp",
            "jsonrpccpp-common",
            "jsonrpccpp-client",
            "microhttpd",
            "boost_program_options",
        ],
        use=[
            "map-lib-base",
            "ant-lib-base",
        ],
    )
