#!/usr/bin/env python
# encoding: utf-8


def build(ctx):
    ctx.program(
        target="is_printable_ut",
        source=[
            "is_printable_ut.cpp",
        ],
    )
    ctx(
        rule="${SRC}",
        source="is_printable_ut",
    )
