#!/usr/bin/env python
# encoding: utf-8


def build(ctx):
    ctx(
        rule=(
            "${JSONRPCSTUB} ${SRC} "
            " --cpp-server=Map::JsonRPCServer"
            " --cpp-server-file=${TGT}"
        ),
        source="rpc_spec.json",
        target="server.h",
    )
    ctx(
        rule=(
            "${JSONRPCSTUB} ${SRC} "
            " --cpp-client=Map::JsonRPCClient"
            " --cpp-client-file=${TGT}"
        ),
        source="rpc_spec.json",
        target="client.h",
    )
